### ISSUE TITLE
Cannot Start the Application with `site_encrypt`

### ISSUE THREAD

**Issue by suprafly** [sasa1977/site_encrypt#48] opened 2023-03-29 21:34 UTC
I am running into some trouble getting `site_encrypt` up and running on Phoenix `1.7.0`.

I have followed the docs in the repo's `README`, but when I run `iex -S mix phx.server` I get the following error, 

```
Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Compiling 1 file (.ex)
[info] Running NoeticFlowWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Running NoeticFlowWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4040 (https)
[notice] Application noetic_flow exited: NoeticFlow.Application.start(:normal, []) returned an error: shutdown: failed to start child: SiteEncrypt.Phoenix
    ** (EXIT) an exception was raised:
        ** (RuntimeError) could not find persistent term for endpoint NoeticFlowWeb.Endpoint. Make sure your endpoint is started and note you cannot access endpoint functions at compile-time
            (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:527: NoeticFlowWeb.Endpoint.persistent!/0
            (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:535: NoeticFlowWeb.Endpoint.url/0
            (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:404: Phoenix.Endpoint.Supervisor.log_access_url/2
            (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:17: Phoenix.Endpoint.Supervisor.start_link/3
            (parent 0.12.1) lib/parent.ex:646: Parent.start_validated_child/2
            (parent 0.12.1) lib/parent.ex:375: Parent.start_child/2
            (parent 0.12.1) lib/parent.ex:396: anonymous fn/1 in Parent.start_all_children!/1
            (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
            (site_encrypt 0.5.0) lib/site_encrypt/adapter.ex:56: SiteEncrypt.Adapter.init/1
            (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[notice] Application makeup_python exited: :stopped
[notice] Application makeup_elixir exited: :stopped
[notice] Application nimble_publisher exited: :stopped
[notice] Application makeup exited: :stopped
[notice] Application nimble_parsec exited: :stopped
[notice] Application earmark exited: :stopped
[notice] Application earmark_parser exited: :stopped
[notice] Application site_encrypt exited: :stopped
[notice] Application x509 exited: :stopped
[notice] Application parent exited: :stopped
[notice] Application jose exited: :stopped
[notice] Application plug_cowboy exited: :stopped
[notice] Application cowboy_telemetry exited: :stopped
[notice] Application cowboy exited: :stopped
[notice] Application ranch exited: :stopped
[notice] Application cowlib exited: :stopped
[notice] Application gettext exited: :stopped
[notice] Application expo exited: :stopped
[notice] Application telemetry_poller exited: :stopped
[notice] Application finch exited: :stopped
[notice] Application nimble_options exited: :stopped
[notice] Application nimble_pool exited: :stopped
[notice] Application mint exited: :stopped
[notice] Application hpax exited: :stopped
[notice] Application swoosh exited: :stopped
[notice] Application jason exited: :stopped
[notice] Application xmerl exited: :stopped
[notice] Application tailwind exited: :stopped
[notice] Application esbuild exited: :stopped
[notice] Application phoenix_live_dashboard exited: :stopped
[notice] Application telemetry_metrics exited: :stopped
[notice] Application heroicons exited: :stopped
[notice] Application phoenix_live_view exited: :stopped
[notice] Application phoenix_live_reload exited: :stopped
[notice] Application file_system exited: :stopped
[notice] Application phoenix_html exited: :stopped
[notice] Application phoenix exited: :stopped
[notice] Application castore exited: :stopped
[notice] Application websock_adapter exited: :stopped
[notice] Application websock exited: :stopped
[notice] Application phoenix_template exited: :stopped
[notice] Application phoenix_pubsub exited: :stopped
[notice] Application plug exited: :stopped
[notice] Application telemetry exited: :stopped
[error] GenServer NoeticFlowWeb.Endpoint terminating
** (RuntimeError) could not find persistent term for endpoint NoeticFlowWeb.Endpoint. Make sure your endpoint is started and note you cannot access endpoint functions at compile-time
    (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:527: NoeticFlowWeb.Endpoint.persistent!/0
    (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:535: NoeticFlowWeb.Endpoint.url/0
    (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:404: Phoenix.Endpoint.Supervisor.log_access_url/2
    (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:17: Phoenix.Endpoint.Supervisor.start_link/3
    (parent 0.12.1) lib/parent.ex:646: Parent.start_validated_child/2
    (parent 0.12.1) lib/parent.ex:375: Parent.start_child/2
    (parent 0.12.1) lib/parent.ex:396: anonymous fn/1 in Parent.start_all_children!/1
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (site_encrypt 0.5.0) lib/site_encrypt/adapter.ex:56: SiteEncrypt.Adapter.init/1
    (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
    (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.532.0>, {%RuntimeError{message: "could not find persistent term for endpoint NoeticFlowWeb.Endpoint. Make sure your endpoint is started and note you cannot access endpoint functions at compile-time"}, [{NoeticFlowWeb.Endpoint, :persistent!, 0, [file: 'lib/phoenix/endpoint.ex', line: 527, error_info: %{module: Exception}]}, {NoeticFlowWeb.Endpoint, :url, 0, [file: 'lib/phoenix/endpoint.ex', line: 535]}, {Phoenix.Endpoint.Supervisor, :log_access_url, 2, [file: 'lib/phoenix/endpoint/supervisor.ex', line: 404]}, {Phoenix.Endpoint.Supervisor, :start_link, 3, [file: 'lib/phoenix/endpoint/supervisor.ex', line: 17]}, {Parent, :start_validated_child, 2, [file: 'lib/parent.ex', line: 646]}, {Parent, :start_child, 2, [file: 'lib/parent.ex', line: 375]}, {Parent, :"-start_all_children!/1-fun-0-", 1, [file: 'lib/parent.ex', line: 396]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]}, {SiteEncrypt.Adapter, :init, 1, [file: 'lib/site_encrypt/adapter.ex', line: 56]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: {:state, {:local, NoeticFlowWeb.Endpoint}, :one_for_one, {[#Reference<0.2657556207.3726114817.97326>, #Reference<0.2657556207.3726114817.97325>, Plug.Cowboy.Drainer, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTPS}, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTP}, Phoenix.LiveView.Socket, Phoenix.LiveReloader.Socket, Phoenix.Config], %{Phoenix.Config => {:child, #PID<0.534.0>, Phoenix.Config, {Phoenix.Config, :start_link, [{NoeticFlowWeb.Endpoint, [endpoint_id: "l+yjKGSrW5Is1JKQcv5rqw", pubsub_server: NoeticFlow.PubSub, https: [keyfile: "/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/privkey.pem", certfile: "/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/cert.pem", cacertfile: "/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/chain.pem"], otp_app: :noetic_flow, cache_static_manifest: nil, reloadable_apps: nil, reloadable_compilers: [:gettext, :elixir, :app], static_url: nil, cache_manifest_skip_vsn: false, force_watchers: false, url: [path: "/", host: "localhost"], render_errors: [view: NoeticFlowWeb.ErrorView, accepts: ["html"], formats: [html: NoeticFlowWeb.ErrorHTML, json: NoeticFlowWeb.ErrorJSON], layout: false], pubsub_server: NoeticFlow.PubSub, live_view: [signing_salt: "ALzV80lI"], http: [ip: {127, 0, 0, 1}, port: 4000], check_origin: false, code_reloader: true, debug_errors: true, secret_key_base: "6M4UFzG0jh6HWrgWaocPBioYTxu76K6P/EMhuocIUjhJzT6UFRUjHNHVHxDIT2zc", watchers: [esbuild: {Esbuild, :install_and_run, [:default, ["--sourcemap=inline", "--watch"]]}, tailwind: {Tailwind, :install_and_run, [:default, ["--watch"]]}], live_reload: [patterns: [~r/priv\/static\/.*(js|css|png|jpeg|jpg|gif|svg)$/, ~r/priv\/gettext\/.*(po)$/, ~r/priv\/posts\/*\/.*(md)$/, ~r/lib\/noetic_flow_web\/(live|views)\/.*(ex)$/, ~r/lib\/noetic_flow_web\/templates\/.*(eex)$/]], server: true], [endpoint_id: "l+yjKGSrW5Is1JKQcv5rqw", pubsub_server: NoeticFlow.PubSub, otp_app: :noetic_flow, code_reloader: false, debug_errors: false, render_errors: [view: NoeticFlowWeb.ErrorView, accepts: ["html"], layout: false], cache_static_manifest: nil, check_origin: true, http: false, https: false, reloadable_apps: nil, reloadable_compilers: [:gettext, :elixir, :app], secret_key_base: nil, static_url: nil, url: [host: "localhost", path: "/"], cache_manifest_skip_vsn: false, watchers: [], force_watchers: false], [name: NoeticFlowWeb.Endpoint.Config]}]}, :permanent, false, 5000, :worker, [Phoenix.Config]}, Phoenix.LiveReloader.Socket => {:child, #PID<0.535.0>, Phoenix.LiveReloader.Socket, {Phoenix.Socket.PoolSupervisor, :start_link, [{NoeticFlowWeb.Endpoint, Phoenix.LiveReloader.Socket, 8}]}, :permanent, false, :infinity, :supervisor, [Phoenix.Socket.PoolSupervisor]}, Phoenix.LiveView.Socket => {:child, #PID<0.544.0>, Phoenix.LiveView.Socket, {Phoenix.Socket.PoolSupervisor, :start_link, [{NoeticFlowWeb.Endpoint, Phoenix.LiveView.Socket, 8}]}, :permanent, false, :infinity, :supervisor, [Phoenix.Socket.PoolSupervisor]}, Plug.Cowboy.Drainer => {:child, #PID<0.761.0>, Plug.Cowboy.Drainer, {Plug.Cowboy.Drainer, :start_link, [[refs: [NoeticFlowWeb.Endpoint.HTTP, NoeticFlowWeb.Endpoint.HTTPS]]]}, :permanent, false, 5000, :worker, [Plug.Cowboy.Drainer]}, #Reference<0.2657556207.3726114817.97325> => {:child, #PID<0.762.0>, #Reference<0.2657556207.3726114817.97325>, {Phoenix.Endpoint.Watcher, :start_link, [esbuild: {Esbuild, :install_and_run, [:default, ["--sourcemap=inline", "--watch"]]}]}, :transient, false, 5000, :worker, [Phoenix.Endpoint.Watcher]}, #Reference<0.2657556207.3726114817.97326> => {:child, #PID<0.763.0>, #Reference<0.2657556207.3726114817.97326>, {Phoenix.Endpoint.Watcher, :start_link, [tailwind: {Tailwind, :install_and_run, [:default, ["--watch"]]}]}, :transient, false, 5000, :worker, [Phoenix.Endpoint.Watcher]}, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTP} => {:child, #PID<0.553.0>, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTP}, {Phoenix.Endpoint.Cowboy2Adapter, :start_link, [:http, NoeticFlowWeb.Endpoint, {:ranch_listener_sup, :start_link, [NoeticFlowWeb.Endpoint.HTTP, :ranch_tcp, %{max_connections: 16384, num_acceptors: 100, socket_opts: [ip: {127, 0, 0, 1}, port: 4000]}, :cowboy_clear, %{env: %{dispatch: [{:_, [], [{:_, [], Plug.Cowboy.Handler, {Phoenix.Endpoint.SyncCodeReloadPlug, {NoeticFlowWeb.Endpoint, []}}}]}]}, stream_handlers: [:cowboy_telemetry_h, :cowboy_stream_h]}]}]}, :permanent, false, :infinity, :supervisor, [:ranch_listener_sup]}, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTPS} => {:child, #PID<0.656.0>, {:ranch_listener_sup, NoeticFlowWeb.Endpoint.HTTPS}, {Phoenix.Endpoint.Cowboy2Adapter, :start_link, [:https, NoeticFlowWeb.Endpoint, {:ranch_listener_sup, :start_link, [NoeticFlowWeb.Endpoint.HTTPS, :ranch_ssl, %{max_connections: 16384, num_acceptors: 100, socket_opts: [alpn_preferred_protocols: ["h2", "http/1.1"], next_protocols_advertised: ["h2", "http/1.1"], reuse_sessions: true, secure_renegotiate: true, cacertfile: '/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/chain.pem', certfile: '/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/cert.pem', keyfile: '/home/suprafly/projects/noetic_flow/tmp/site_encrypt_db/certs/noeticflow.com/privkey.pem', port: 4040]}, :cowboy_tls, %{env: %{dispatch: [{:_, [], [{:_, [], Plug.Cowboy.Handler, {Phoenix.Endpoint.SyncCodeReloadPlug, {NoeticFlowWeb.Endpoint, []}}}]}]}, stream_handlers: [:cowboy_telemetry_h, :cowboy_stream_h]}]}]}, :permanent, false, :infinity, :supervisor, [:ranch_listener_sup]}}}, :undefined, 3, 5, [], 0, :never, Phoenix.Endpoint.Supervisor, {:noetic_flow, NoeticFlowWeb.Endpoint, []}}
[notice] Application plug_crypto exited: :stopped
[notice] Application mime exited: :stopped
[notice] Application eex exited: :stopped
[notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application noetic_flow: NoeticFlow.Application.start(:normal, []) returned an error: shutdown: failed to start child: SiteEncrypt.Phoenix
    ** (EXIT) an exception was raised:
        ** (RuntimeError) could not find persistent term for endpoint NoeticFlowWeb.Endpoint. Make sure your endpoint is started and note you cannot access endpoint functions at compile-time
            (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:527: NoeticFlowWeb.Endpoint.persistent!/0
            (noetic_flow 0.1.0) lib/phoenix/endpoint.ex:535: NoeticFlowWeb.Endpoint.url/0
            (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:404: Phoenix.Endpoint.Supervisor.log_access_url/2
            (phoenix 1.7.0) lib/phoenix/endpoint/supervisor.ex:17: Phoenix.Endpoint.Supervisor.start_link/3
            (parent 0.12.1) lib/parent.ex:646: Parent.start_validated_child/2
            (parent 0.12.1) lib/parent.ex:375: Parent.start_child/2
            (parent 0.12.1) lib/parent.ex:396: anonymous fn/1 in Parent.start_all_children!/1
            (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
            (site_encrypt 0.5.0) lib/site_encrypt/adapter.ex:56: SiteEncrypt.Adapter.init/1
            (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Any ideas on why the Endpoint is not being found by the `persistent!/0` call here?

**Comment by damonvjanis** [comment] 2023-03-30 03:15
@suprafly I've been [tracing the same error](https://github.com/sasa1977/site_encrypt/issues/47), but in the `test` environment (it was working fine for me in `dev`), and then I realized that it wasn't working in a fresh `mix phx.new` app in `test` OR `dev`. I was able to isolate the config differences between the app I'd been working on and my fresh `mix phx.new` app, and in the app I was working on it had a `https: [port: 4001]` line in `dev.exs` and the fresh app didn't have any `https` config.

I added that line to my Endpoint config in `test.exs` and the tests ran successfully, so I'm feeling good that it's the fix.

I haven't been able to trace it all the way through site_encrypt yet (and now that I have a working solution I'm not sure I'll have the motivation to haha), but it seems reasonable that for a library that helps you configure SSL, you'd have to provide an `https` port for it to work properly (even in dev and test).

**Comment by suprafly** [comment] 2023-03-30 05:35
[I've created a very simple example repo illustrating the problem.](https://github.com/suprafly/phoenix_ssl_demo)

**Comment by suprafly** [comment] 2023-03-30 05:45
@damonvjanis Thanks for all of the info that you've dug up. I have been also down the rabbithole, but not fully understanding the cause. In my case, there does not seem to be a `~p` causing the error to raise, but it does look like we have the same error.

From my own digging, it seems like the `Endpoint` is not being registered in a way that allows it to be identified later on. I was wondering if the error is bubbling up from the `parent` dependency. I can see that the endpoint's `init/2` function is called and it responds, and then later that the error comes from a deeply nested `start_link` in the `Parent.Genserver` call.

I was not able to get your workaround to work for me in either dev or test. Cowboy complains about needing keyfile anc cert, and even when I give it them it does not cooperate.

**Comment by sasa1977** [comment] 2023-03-30 10:38
btw. this is an issue of Phoenix. Below is a minimal elixir script that can reproduce the issue using just phoenix (i.e. without site_encrypt)and plain http:

```elixir
# modified version of https://github.com/wojtekmach/mix_install_examples

Application.put_env(:phoenix, :json_library, Jason)

Application.put_env(:sample, SamplePhoenix.Endpoint,
  # note that port is missing, which will cause the cryptic error during the endpoint start
  http: [ip: {127, 0, 0, 1}],
  server: true,
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"}
])

defmodule SamplePhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
end

{:ok, _} = Supervisor.start_link([SamplePhoenix.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

Basically, the cryptic "could not find persistent term" error occurs if http (or https) config is provided without port. I wonder if it would be better to fix the behaviour (i.e. to print a more informative error) in Phoenix, because it's possible to trigger it without site_encrypt.

**Comment by sasa1977** [comment] 2023-03-30 16:11
I [reported this to Phoenix](https://github.com/phoenixframework/phoenix/issues/5389) and it has been solved there, so I'm closing the issue here.

**Closed by sasa1977** 2023-03-30 16:11 UTC

**Comment by suprafly** [comment] 2023-03-30 18:13
Wow, great find. Thanks so much @sasa1977

**Comment by Hermanverschooten** [comment] 2023-04-06 14:19
Just for posterity, I had to add a `https:` section with a `:port`  in my test config to make them pass again.
